version: "3"
services:

  libre-chat:
    # build: .
    image: ghcr.io/vemonet/libre-chat:main
    volumes:
      - ./:/app # Share the whole directory with chat.yml, models, vectorstore
    ports:
      - 8000:8000
    environment:
      - LIBRECHAT_WORKERS=8
    # entrypoint: uvicorn tests.main:app --reload
    # networks:
    #   - no-internet
    # shm_size: '16g'
    # deploy:  # Enable 1 GPU in this container
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

# networks:
#   no-internet:
#     driver: bridge
#     internal: true
