name: 💡 Feature request
description: Suggest an idea.
labels: ['enhancement']

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What do you want to improve? Why?
      placeholder: Feature description
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: An idea of implementation
      description: Describe how you would implement it, if you have some ideas
      placeholder: |
        Your ideas, link to relevant packages...

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or comment here.
